name: build webapp
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build index page
        run: echo "<html><body><h1>HelloWorld from artifacts!</h1></body></html>" > index.html
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: index-file
          path: index.html
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: index-file
          path: home
      - name: list artifacts
        run: |
          ls -lR
          more home/index.html


